/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package des_sim;

import java.io.*;
import java.util.Calendar;
import javax.swing.*;

/**
 *
 * @author Lester
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        FileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EnRadio = new javax.swing.JRadioButton();
        DeRadio = new javax.swing.JRadioButton();
        KeyText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InfoArea = new javax.swing.JTextArea();
        Clr0Button = new javax.swing.JButton();
        IVText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Ld1Button = new javax.swing.JButton();
        Ld2Button = new javax.swing.JButton();
        Clr1Button = new javax.swing.JButton();
        Clr2Button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Text1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Text2 = new javax.swing.JTextArea();
        ResetButton = new javax.swing.JButton();
        BitAButton = new javax.swing.JButton();
        RunButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DES Simulator");

        jLabel1.setText("CSCI-6541 DES Simulator");

        jLabel2.setText("Encryption/Decryption");

        jLabel3.setText("Mode of Operation");

        jLabel4.setText("Key (0x)");

        buttonGroup1.add(EnRadio);
        EnRadio.setSelected(true);
        EnRadio.setText("Encrypt");

        buttonGroup1.add(DeRadio);
        DeRadio.setText("Decrypt");

        List.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "DES(Test)", "ECB", "CBC", "CFB-8", "OFB-8", "CNT" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        List.setSelectedIndex(0);
        jScrollPane1.setViewportView(List);

        jLabel5.setText("Info");

        jScrollPane2.setToolTipText("");
        jScrollPane2.setAutoscrolls(true);

        InfoArea.setEditable(false);
        InfoArea.setColumns(5);
        InfoArea.setRows(5);
        jScrollPane2.setViewportView(InfoArea);

        Clr0Button.setText("Clear");
        Clr0Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clr0ButtonMouseClicked(evt);
            }
        });

        jLabel6.setText("IV or Counter (0x)");

        Ld1Button.setText("Load (Input)");
        Ld1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ld1ButtonMouseClicked(evt);
            }
        });

        Ld2Button.setText("Load (Output)");
        Ld2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ld2ButtonMouseClicked(evt);
            }
        });

        Clr1Button.setText("Clear");
        Clr1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clr1ButtonMouseClicked(evt);
            }
        });

        Clr2Button.setText("Clear");
        Clr2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clr2ButtonMouseClicked(evt);
            }
        });

        Text1.setEditable(false);
        Text1.setColumns(15);
        Text1.setRows(5);
        jScrollPane3.setViewportView(Text1);

        Text2.setEditable(false);
        Text2.setColumns(15);
        Text2.setRows(5);
        jScrollPane4.setViewportView(Text2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Ld2Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clr2Button))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Ld1Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Clr1Button)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ld1Button)
                    .addComponent(Clr1Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ld2Button)
                    .addComponent(Clr2Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(KeyText)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(EnRadio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(DeRadio))
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Clr0Button))
                                .addComponent(IVText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(EnRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(KeyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IVText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Clr0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        ResetButton.setText("Reset");
        ResetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetButtonMouseClicked(evt);
            }
        });

        BitAButton.setText("BitA");
        BitAButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BitAButtonMouseClicked(evt);
            }
        });

        RunButton.setText("Run");
        RunButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RunButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RunButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BitAButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BitAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RunButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RunButtonMouseClicked
        // TODO add your handling code here:
        //initialize key
        String key="";
        //set iv
        if(!KeyText.getText().equals(""))key=Long.toBinaryString(Long.parseLong(KeyText.getText(), 16));
        String iv="";
        //set text (plain/cipher)
        if(!IVText.getText().equals(""))iv=Long.toBinaryString(Long.parseLong(IVText.getText(), 16));
        String text=Text1.getText().replaceAll("\n","");
        //empty output window
        Text2.setText("");
        
        //do complemention first
        key=TextBlock.Complement(key, 64);
        iv=TextBlock.Complement(iv, 64);
        OpModes OP=new OpModes(text,key,iv);
        
        //set encryption/decryption mode
        String mode;
        if(buttonGroup1.isSelected(EnRadio.getModel())){
            mode="En";
            OP.setEN();
            InfoArea.append("Encryption mode now selected\n");
        }
        else{
            mode="De";
            OP.setDE();
            InfoArea.append("Decryption mode now selected\n");
        }   
        
        //Info notification        
        InfoArea.append("The key is (0x)"+KeyText.getText()+"\n");
        
        //Runtime Watch
        long timer=System.currentTimeMillis();
        
        //Implementation the modes of operation
        String op="";
        int sel=List.getAnchorSelectionIndex();
        switch(sel){
            //DES Test
            case 0:
                op="DES";
                InfoArea.append("Operation Mode is DES (Test)\n"+
                        "In this mode, the system only handles the first block(64 bits)\n");
                OP.DES();
                Display(OP,timer);
                break;
            //ECB
            case 1:
                op="ECB";
                InfoArea.append("Operation Mode is ECB, running......\n");
                OP.ECB();
                Display(OP,timer);
                break;
            //CBC
            case 2:
                op="CBC";
                InfoArea.append("Operation Mode is CBC, running......\n");
                OP.CBC();
                Display(OP,timer);
                break;
            //CFB-8
            case 3:
                op="CFB-8";
                InfoArea.append("Operation Mode is CFB-8, running......\n");
                OP.CFB();
                Display(OP,timer);
                break;
            //OFB-8
            case 4:
                op="OFB-8";
                InfoArea.append("Operation Mode is OFB-8, running......\n");
                OP.OFB();
                Display(OP,timer);
                break;
            //CNT
            case 5:
                op="CNT";
                InfoArea.append("Operation Mode is CNT, running......\n");
                OP.CNT();
                Display(OP,timer);
                break;
            //default
            default:
                InfoArea.append("Mode of Operation Selection Error\n");
                break;                
        }
        
        //file output
        BufferedReader br=null;
		BufferedWriter bw=null;
		try{
                     bw=new BufferedWriter(new FileWriter(name+"_"+op+"_"+mode+".txt"));//String output stream
                     String str=Text2.getText().replaceAll("\n", "\r\n");
                     bw.write(str);
                     bw.flush();
		} 
                catch (IOException e){
                     e.printStackTrace();
		}
                finally{
                     try{
                         bw.close();
                     } 
                     catch (IOException e){
                          e.printStackTrace();
                     }

                }
    }//GEN-LAST:event_RunButtonMouseClicked

    private void Ld2ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ld2ButtonMouseClicked
        // TODO add your handling code here:
        int returnVal = FileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = FileChooser.getSelectedFile();
            try {
                FileReader filereader = new FileReader(file);
                Text2.read( new FileReader( file.getAbsolutePath() ), null );
                
            } catch (IOException ex) {
                System.out.println("problem accessing file " + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_Ld2ButtonMouseClicked

    private void Ld1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ld1ButtonMouseClicked
        // TODO add your handling code here:
        //open file browser
        int returnVal = FileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = FileChooser.getSelectedFile();
            try {
                FileReader filereader = new FileReader(file);
                Text1.read( new FileReader( file.getAbsolutePath() ), null );
                name=file.getAbsolutePath();
                name=name.substring(0, name.lastIndexOf("."));
            } catch (IOException ex) {
                System.out.println("problem accessing file " + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_Ld1ButtonMouseClicked

    private void BitAButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BitAButtonMouseClicked
        // TODO add your handling code here:
        String a,b;
        int diff=0;
        int[] counter={0,0,0,0};
        a=Text1.getText().replaceAll("\n", "");
        b=Text2.getText().replaceAll("\n", "");
        for(int i=0;i<a.length();i++){
            if(a.substring(i, i+1).equals("0"))counter[0]++;
            if(a.substring(i, i+1).equals("1"))counter[1]++;
            if(b.substring(i, i+1).equals("0"))counter[2]++;
            if(b.substring(i, i+1).equals("1"))counter[3]++;
            if(!a.substring(i, i+1).equals(b.substring(i, i+1)))diff++;
        }
        InfoArea.append("Analysis Result:\n"
                +"Total length of Text A and B: "+a.length()+"\n"
                +counter[0]+" bits of '0' & "+counter[1]+" bits of '1' in Text A\n"
                +counter[2]+" bits of '0' & "+counter[3]+" bits of '1' in Text B\n"
                +diff+" different bits between Text A & B\n"
        );
    }//GEN-LAST:event_BitAButtonMouseClicked

    private void Clr0ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clr0ButtonMouseClicked
        // TODO add your handling code here:
        InfoArea.setText("");
    }//GEN-LAST:event_Clr0ButtonMouseClicked

    private void Clr1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clr1ButtonMouseClicked
        // TODO add your handling code here:
        Text1.setText("");
    }//GEN-LAST:event_Clr1ButtonMouseClicked

    private void Clr2ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clr2ButtonMouseClicked
        // TODO add your handling code here:
        Text2.setText("");
    }//GEN-LAST:event_Clr2ButtonMouseClicked

    private void ResetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseClicked
        // TODO add your handling code here:        
        buttonGroup1.setSelected(EnRadio.getModel(), true);
        List.setSelectedIndex(0);
        KeyText.setText("");
        IVText.setText("");
        InfoArea.setText("");
        Text1.setText("");
        Text2.setText("");
    }//GEN-LAST:event_ResetButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    //Display routine
    private void Display(OpModes OP, long timer){
        String content=OP.getOutput();
        int line=content.length()/32;
        for(int i=0;i<line;i++){
            Text2.append(content.substring(i*32, i*32+32)+"\n");            
        }
        if(content.length()%32!=0){
            Text2.append(content.substring(line*32)+"\n");
        }
        
        long timer1=System.currentTimeMillis();
        long Runtime=timer1-timer;
        InfoArea.append("Encryption/Decryption Completed\n"+
        "Runtime: "+Runtime+"ms\n\n");
    }
    
    //file path
    private String name;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BitAButton;
    private javax.swing.JButton Clr0Button;
    private javax.swing.JButton Clr1Button;
    private javax.swing.JButton Clr2Button;
    private javax.swing.JRadioButton DeRadio;
    private javax.swing.JRadioButton EnRadio;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JTextField IVText;
    private javax.swing.JTextArea InfoArea;
    private javax.swing.JTextField KeyText;
    private javax.swing.JButton Ld1Button;
    private javax.swing.JButton Ld2Button;
    private javax.swing.JList List;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton RunButton;
    private javax.swing.JTextArea Text1;
    private javax.swing.JTextArea Text2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
