/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calculator;

/**
 *
 * @author Lester
 */
public class Calculator extends javax.swing.JFrame {
    private boolean start=true;
    private double result=0;
    private String lastCommand="=";
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        BtnDivide = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        BtnMultiply = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        BtnMinus = new javax.swing.JButton();
        Btn0 = new javax.swing.JButton();
        BtnPoint = new javax.swing.JButton();
        BtnEqual = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RdBtnScientific = new javax.swing.JRadioButtonMenuItem();
        RdBtnStandard = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        display.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new java.awt.GridLayout(4, 4));

        Btn7.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Btn7.setText("7");
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert(evt);
            }
        });
        jPanel2.add(Btn7);

        Btn8.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Btn8.setText("8");
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert(evt);
            }
        });
        jPanel2.add(Btn8);

        Btn9.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Btn9.setText("9");
        Btn9.setToolTipText("");
        Btn9.setName(""); // NOI18N
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert(evt);
            }
        });
        jPanel2.add(Btn9);

        BtnDivide.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        BtnDivide.setText("/");
        BtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Command(evt);
            }
        });
        jPanel2.add(BtnDivide);

        Btn6.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Btn6.setText("6");
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert(evt);
            }
        });
        jPanel2.add(Btn6);

        Btn5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Btn5.setText("5");
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert(evt);
            }
        });
        jPanel2.add(Btn5);

        Btn4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Btn4.setText("4");
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert(evt);
            }
        });
        jPanel2.add(Btn4);

        BtnMultiply.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        BtnMultiply.setText("*");
        BtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Command(evt);
            }
        });
        jPanel2.add(BtnMultiply);

        Btn3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Btn3.setText("3");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert(evt);
            }
        });
        jPanel2.add(Btn3);

        Btn2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Btn2.setText("2");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert(evt);
            }
        });
        jPanel2.add(Btn2);

        Btn1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Btn1.setText("1");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert(evt);
            }
        });
        jPanel2.add(Btn1);

        BtnMinus.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        BtnMinus.setText("-");
        BtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Command(evt);
            }
        });
        jPanel2.add(BtnMinus);

        Btn0.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Btn0.setText("0");
        Btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert(evt);
            }
        });
        jPanel2.add(Btn0);

        BtnPoint.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        BtnPoint.setText(".");
        BtnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert(evt);
            }
        });
        jPanel2.add(BtnPoint);

        BtnEqual.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        BtnEqual.setText("=");
        BtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Command(evt);
            }
        });
        jPanel2.add(BtnEqual);

        BtnAdd.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        BtnAdd.setText("+");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Command(evt);
            }
        });
        jPanel2.add(BtnAdd);

        jMenu1.setText("View");

        buttonGroup1.add(RdBtnScientific);
        RdBtnScientific.setSelected(true);
        RdBtnScientific.setText("Scientific");
        jMenu1.add(RdBtnScientific);

        buttonGroup1.add(RdBtnStandard);
        RdBtnStandard.setText("Standard");
        jMenu1.add(RdBtnStandard);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Help");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Insert(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert
        // TODO add your handling code here:
        String input=evt.getActionCommand();
        if(start){
            display.setText("");
            start=false;
        }
        display.setText(display.getText()+input);
    }//GEN-LAST:event_Insert

    private void Command(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Command
        // TODO add your handling code here:
        String input=evt.getActionCommand();
        if(start){
            if(input.equals("-")){
                display.setText(input);
                start=false;
            }
            else{
                lastCommand=input;
            }
        }
        else{
            double number=Double.parseDouble(display.getText());
            if(lastCommand.equals("+"))result+=number;
            else if(lastCommand.equals("-"))result-=number;
            else if(lastCommand.equals("*"))result*=number;
            else if(lastCommand.equals("/"))result/=number;
            else result=number;
            display.setText(""+result);
            lastCommand=input;
            start=true;
        }        
    }//GEN-LAST:event_Command

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AboutFrame af=new AboutFrame();
        af.setLocation(450,200);
        af.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Calculator c=new Calculator();
                c.setLocationByPlatform(true);
                c.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn0;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnDivide;
    private javax.swing.JButton BtnEqual;
    private javax.swing.JButton BtnMinus;
    private javax.swing.JButton BtnMultiply;
    private javax.swing.JButton BtnPoint;
    private javax.swing.JRadioButtonMenuItem RdBtnScientific;
    private javax.swing.JRadioButtonMenuItem RdBtnStandard;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField display;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
