
package com.antra.consume;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CXF", targetNamespace = "http://soap.antra.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CXF {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void createDepartment(
        @WebParam(name = "arg0", partName = "arg0")
        Department arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void deleteProject(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.antra.soap.Project
     */
    @WebMethod
    @WebResult(partName = "return")
    public Project readProject(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void deleteEmployee(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void createProject(
        @WebParam(name = "arg0", partName = "arg0")
        Project arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void updateEmployee(
        @WebParam(name = "arg0", partName = "arg0")
        Employee arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void createEmployee(
        @WebParam(name = "arg0", partName = "arg0")
        Employee arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void deleteDepartment(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.antra.soap.Department
     */
    @WebMethod
    @WebResult(partName = "return")
    public Department readDepartment(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void updateDepartment(
        @WebParam(name = "arg0", partName = "arg0")
        Department arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void updateProject(
        @WebParam(name = "arg0", partName = "arg0")
        Project arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.antra.soap.Employee
     */
    @WebMethod
    @WebResult(partName = "return")
    public Employee readEmployee(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
