
package com.antra.consume;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CXFImplService", targetNamespace = "http://soap.antra.com/", wsdlLocation = "http://localhost:8088/SpringMVCxWS/CXF/service?wsdl")
public class CXFImplService
    extends Service
{

    private final static URL CXFIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CXFIMPLSERVICE_EXCEPTION;
    private final static QName CXFIMPLSERVICE_QNAME = new QName("http://soap.antra.com/", "CXFImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/SpringMVCxWS/CXF/service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CXFIMPLSERVICE_WSDL_LOCATION = url;
        CXFIMPLSERVICE_EXCEPTION = e;
    }

    public CXFImplService() {
        super(__getWsdlLocation(), CXFIMPLSERVICE_QNAME);
    }

    public CXFImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CXFIMPLSERVICE_QNAME, features);
    }

    public CXFImplService(URL wsdlLocation) {
        super(wsdlLocation, CXFIMPLSERVICE_QNAME);
    }

    public CXFImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CXFIMPLSERVICE_QNAME, features);
    }

    public CXFImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CXFImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CXF
     */
    @WebEndpoint(name = "CXFImplPort")
    public CXF getCXFImplPort() {
        return super.getPort(new QName("http://soap.antra.com/", "CXFImplPort"), CXF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CXF
     */
    @WebEndpoint(name = "CXFImplPort")
    public CXF getCXFImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.antra.com/", "CXFImplPort"), CXF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CXFIMPLSERVICE_EXCEPTION!= null) {
            throw CXFIMPLSERVICE_EXCEPTION;
        }
        return CXFIMPLSERVICE_WSDL_LOCATION;
    }

}
